package main

type Client interface {

	// Ping does ping pong with the API server at /
	Ping()
	// InitiateWithdrawal initiates a withdrawal from River Platform API by paying a specific invoice
	InitiateWithdrawal(amount int, invoice, currency, network string, fee_limit int)
	// GetWithdrawal returns a withdrawal based on the passed withdrawal_id
	GetWithdrawal(withdrawal_id string)
	// CreateDepositInvoice creates an invoice to enable deposits to River Platform
	CreateDepositInvoice(amount int, label, network string)
	// GetDepositInvoices queries a list of invoices generated by River Platform
	GetDepositInvoices(limit, next_timestamp int)
	// GetDeposits returns a list of deposits (settled invoices) to River Platform
	GetDeposits(limit, next_timestamp int)
	// SubscribeToWebhook subscribes to a webhook
	SubscribeToWebhook(callback_url string)
	// GetSubscribedWebhook queries subscribed webhook
	GetSubscribedWebhook()
	// DeleteWebhook deletes the existing webhook
	DeleteWebhook()
	// DecodeInvoice decodes a Lightning Invoice using River Platform using `lncli decodepayreq`
	DecodeInvoice(invoice string)
	// EstimateLightningFee estimates Lightning Fee of an invoice using `lncli`
	EstimateLightningFee(invoice string, amount int)
}
